### ISSUE TITLE
[Error] No matching export in "node_modules/svelte-ux/dist/index.js" for import "getDuration"

### ISSUE THREAD

**Issue by OWLYone** [techniq/layerchart#127]
In a vanilla installation following the documentation to the letter: 

- Vanilla installation of Sveltekit
- Svelte-UX installed with Svelte-Add
- Tailwind setup with Svelte-Add + Config updated
- LayerChart and D3 added as per "with Svelte-UX" instruction

I'm getting the following Error:
`✘ [ERROR] No matching export in "node_modules/svelte-ux/dist/index.js" for import "getDuration"

    node_modules/layerchart/dist/utils/ticks.js:3:33:
      3 │ import { formatDate, PeriodType, getDuration } from 'svelte-ux';`

And indeed, it does not look like it's properly exported/imported... Or I'm missing something?

**Comment by techniq** [comment]
Hey @OWLYone 👋, thanks for checking out LayerChart.  That's interesting you're receiving that error.  Could you share your repo to see if I can reproduce locally?

**Comment by OWLYone** [comment]
Sure, made a fresh step-by-step, the same effect. 

[Tryout-Layerchart with SvelteUX](https://github.com/OWLYone/tryout-layerchart/blob/084d0fbebebc4c26e83d3873e1a42354261057bd/src/routes/%2Bpage.svelte)

`✘ [ERROR] No matching export in "node_modules/svelte-ux/dist/index.js" for import "getDuration"

    node_modules/layerchart/dist/utils/ticks.js:3:33:
      3 │ import { formatDate, PeriodType, getDuration } from 'svelte-ux';
        ╵                                  ~~~~~~~~~~~

16:15:01 [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/layerchart/dist/utils/ticks.js:3:33: ERROR: No matching export in "node_modules/svelte-ux/dist/index.js" for import "getDuration"
    at failureErrorWithLog (F:\...\tryout-layerchart\node_modules\esbuild\lib\main.js:1651:15)
    at F:\...\tryout-layerchart\node_modules\esbuild\lib\main.js:1059:25
    at F:\...\tryout-layerchart\node_modules\esbuild\lib\main.js:1527:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
`

**Comment by techniq** [comment]
@OWLYone That was interesting... definitely something that needed [fixed](https://github.com/techniq/svelte-ux/commit/9afe883235de2d4bf2c3e76200c995e05e4d1a49) but not sure why it didn't show up in the build or other projects.

You should be good after updating to Svelte UX to `0.61.2` and LayerChart to `0.32.1`.

![image](https://github.com/techniq/layerchart/assets/177476/214d484a-a1fd-4bab-aedd-ec4170138d34)

Btw, we have a [Discord](https://discord.gg/697JhMPD3t) server if you run into any other problems.  Github issues are good to, but Discord can be faster to iterate.
