### ISSUE TITLE
Suggestion: use "alias" so page source / example match usage

### ISSUE THREAD

**Issue by CaptainCodeman** [techniq/layerchart#177]
The [getting-started page](https://www.layerchart.com/getting-started) explain how examples / page source will need different imports:

> The page source will show:

```ts
import Chart, { Svg } from '$lib/components/Chart.svelte';
import Axis from '$lib/components/Axis.svelte';
import Bars from '$lib/components/Bars.svelte';
```

> If you followed instructions to `npm install layerchart` your code should be:

```ts
import { Chart, Svg, Axis, Bars } from 'layerchart';
```

Using the [alias configuration option](https://kit.svelte.dev/docs/configuration#alias) would allow the internal code to import from 'layerchart' which might make things clearer / simpler.

BTW: excellent lib, just exploring it ...

**Comment by CaptainCodeman** [comment]
Oh, maybe a duplicate of https://github.com/techniq/layerchart/issues/108

**Comment by techniq** [comment]
Thanks @CaptainCodeman.  There has been some exploration in a [PR](https://github.com/techniq/layerchart/pull/151) and need to see if there is any performance regressions (that outweigh the benefits).  Likely there will not be though.

**Comment by CaptainCodeman** [comment]
Sorry for the noise, I should have looked first. I've never noticed any perf issue with that approach (although my libs tend to be smaller). AFAIK there are none and it's just a mapping done at the vite level.

**Comment by techniq** [comment]
As soon as I wrap up the [Brush](https://github.com/techniq/layerchart/pull/175) component I'm going to use `alias` see how it goes.  Will be a good improvement for examples and general development.

**Comment by techniq** [comment]
and no worries about the noise, always nice to gauge interest to help set priorities.

**Comment by CaptainCodeman** [comment]
Yeah, as someone new to the lib it was one thing that tripped me up a little. That and the tailwindcss custom colors that appear to depend on the ux lib.

**Comment by techniq** [comment]
@CaptainCodeman Yeah, improving docs when not using Svelte UX (whether it's Skeleton, shadcn-svelte, standalone, etc) needs to be improved.  Gathering notes in https://github.com/techniq/layerchart/issues/160 to move to the docs once I get more fleshed out. 

Also hoping to gather a lot of [examples](https://github.com/techniq/layerchart/issues/150) of various framework combinations to allow others to use as reference.

**Comment by techniq** [comment]
@CaptainCodeman https://github.com/techniq/layerchart/pull/192 😁
