### ISSUE TITLE
Combo Line/Bar

### ISSUE THREAD

**Issue by alex-way** [techniq/layerchart#225]
Is there any easy way to achieve something like the following?

https://www.chartjs.org/docs/latest/samples/other-charts/combo-bar-line.html

**Comment by techniq** [comment]
Hey @alex-way 👋, have you seen these examples:

- https://www.layerchart.com/docs/examples/Compound
- https://www.layerchart.com/docs/examples/DualAxis

**Comment by alex-way** [comment]
@techniq Ahh the compound is exactly what I'm looking for - Apologies I must've skipped over that in the docs!

**Comment by techniq** [comment]
No worries!  There is also some additional context in this [discussion](https://discord.com/channels/920755200552226868/1260719312004452493/1260812738494730261).  I just created the compound example last night ;)
