### ISSUE TITLE
Setting the width of bar chart bars

### ISSUE THREAD

**Issue by Destaq** [techniq/layerchart#235]
Is it possible to adjust the width of individual bars generated for a bar chart? I noticed a `widthOffset` property in an old commit but that seems to have been since reverted, not sure if there is a current solution?

**Comment by techniq** [comment]
Hey @Destaq 👋, the property is now called `inset` as of [0.25.0](https://github.com/techniq/layerchart/blob/main/packages/layerchart/CHANGELOG.md#0250).  See this [example](https://www.layerchart.com/docs/examples/Columns#multiple_(overlapping))
