### ISSUE TITLE
Remove posthog from dependencies

### ISSUE THREAD

**Issue by coryvirok** [techniq/layerchart#300]
I was excited to try LayerChart but when I installed it I noticed posthog-js was installed as a dependency. I'm guessing this was unintentional. Can it be removed?

**Comment by techniq** [comment]
Awe, good catch!  `posthog-js` is only used for the docs to [track](https://github.com/techniq/layerchart/blob/ab3304be2e81df0752819b9abfcba5fe669cb200/packages/layerchart/src/routes/%2Blayout.svelte#L83-L107) page views, but there was a duplicate reference in `dependencies` (should only be in `devDependencies)`).  It has been [removed](https://github.com/techniq/layerchart/commit/ffd008cc7edac8eed4f7a638dfa973f73fe8b493) and released as [0.60.3](https://github.com/techniq/layerchart/releases/tag/layerchart%400.60.3)
