### ISSUE TITLE
Bug in examples for columns and bars - sorting of date series.

### ISSUE THREAD

**Issue by mattlangeman** [techniq/layerchart#54]
The bar and column date series charts are sorting by the date string (day of week).

![CleanShot 2023-10-13 at 17 17 06](https://github.com/techniq/layerchart/assets/92231/56627065-812f-49c9-b2ae-552553e667f3)

**Comment by techniq** [comment]
Awe, likely a regression from upgrading Layer Cake to 8.0.0 today... 

https://github.com/mhkeller/layercake/releases/tag/v8.0.0

**Comment by mattlangeman** [comment]
Wondering if these examples should be using scaleTime instead of scaleBand. That would fix the sorting issue, but doing so causes the bars to have width=0. I'm thinking changes are needed to createDimensionGetter.

A side benefit is that you could also set the number of ticks. Current the Axis uses the full domain for ticks if it is scaleBand and it gets a bit crowded.

https://github.com/techniq/layerchart/blob/ed042942aff48ffe5d44b3893378b2fbe1178d95/src/lib/components/Axis.svelte#L36-L40

**Comment by techniq** [comment]
Possibly... I know using a band scale with dates isn't optimal (especially with gaps in the data).  

Here is some Observable Plot examples, which has an `interval` option

- https://observablehq.com/@observablehq/plot-ordinal-bar-chart
- https://observablehq.com/@observablehq/plot-ordinal-scale-interval

I opened a LayerCake issue to discuss as well

**Comment by techniq** [comment]
@mattlangeman Btw, improving date handling with band/bar charts was something I was tracing in #21 as well

**Comment by techniq** [comment]
Updated to `8.0.1`, but still seeing the [issue](https://github.com/mhkeller/layercake/issues/151#issuecomment-1763212057) (both in LayerChart, and the LayerCake REPL).

**Comment by techniq** [comment]
Fixed by Layer Cake `8.0.2`, and released as `0.24.3`.
