### ISSUE TITLE
Tooltip issue with localPoint when chart has left padding

### ISSUE THREAD

**Issue by mattlangeman** [techniq/layerchart#55]
### Main Issue
I noticed an issue with the Tooltip when a chart has left padding. The Tooltip has issues picking the correct data point.

### Issue Details
When TooltipContext gets the localPoint, the localX value is never below the value of the left padding for the chart.

https://github.com/techniq/layerchart/blob/5c567e3beed590d097845d5f7e14415068dae0db/src/lib/components/TooltipContext.svelte#L140-L142

This means it does not get the proper xValueAtPoint.

https://github.com/techniq/layerchart/blob/5c567e3beed590d097845d5f7e14415068dae0db/src/lib/components/TooltipContext.svelte#L180

### Solution?
I don't know whether it is as simple as subtracting the left padding to setting localX.

### Screen Recordings
**Line Chart example that has `left: 16`. Not super noticeable.** 
![tooltip-line-chart-left-padding-16](https://github.com/techniq/layerchart/assets/92231/92c505ad-4282-443f-95ff-1dd6dde8be74)

**Line Chart example with `left: 32`. Very noticeable.** 
![tooltip-line-chart-left-padding-32](https://github.com/techniq/layerchart/assets/92231/f2533093-a404-4a86-b646-11a566a0a935)

**Line Chart example with `left: 0`. Removes the issue.**
![tooltip-line-chart-left-padding-0](https://github.com/techniq/layerchart/assets/92231/f123b207-4080-49ea-8f11-1cf8c5b72581)

**Tooltip Interactions example `left: 36` Very noticeable.** 
![tooltip-scatterplot-left-padding-36](https://github.com/techniq/layerchart/assets/92231/c8342a8a-5ede-42e5-a6b3-83ba449abfc1)

**Tooltip Interactions example `left: 0` Removes the issue.**
![tooltip-scatterplot-left-padding-0](https://github.com/techniq/layerchart/assets/92231/c34dbd1c-7ccf-4598-8156-88c6f3582d64)

**localX value when `left: 32`**
![localX-of-TooltipContext](https://github.com/techniq/layerchart/assets/92231/32cfb135-5cc3-4170-bd13-507e8a689d63)

**Comment by techniq** [comment]
@mattlangeman This is now [fixed](https://github.com/techniq/layerchart/commit/d69295a0ec77894e0daf1c1ec08ef337a6eb9460) in `0.24.4`.  I also update `Tooltip` to support `variant` prop with `light`, `dark`, and `none`.  I used `none` to update [Sparkbar](https://www.layerchart.com/docs/examples/Sparkbar) / [Sparkline](https://www.layerchart.com/docs/examples/Sparkline) fixed position examples, as well as [Clipped Area](https://www.layerchart.com/docs/examples/Area#clipped-area-on-tooltip) example

**Comment by mattlangeman** [comment]
Tooltip variant option looks good. Nice to have full control over styling when needed.

The left padding issue also looks fixed, though I'm thinking when mode is `bisect-y` it should be using `$padding.top` instead of `$padding.left`.

https://github.com/techniq/layerchart/blob/d69295a0ec77894e0daf1c1ec08ef337a6eb9460/src/lib/components/TooltipContext.svelte#L191

**Comment by mattlangeman** [comment]
Yeah. I was trying to find examples using `bisect-y`, but didn't see anything. I played around with the [Single Date / Time Example](https://www.layerchart.com/docs/components/Tooltip#single-date-/-time-%3Csmall%3Ex:-scaletime,-y:-scaleband%3C/small%3E), but I don't think you intended that to support `bisect-y`
