### ISSUE TITLE
tight couple with daisyui will block using with other tailwind frameworks 

### ISSUE THREAD

**Issue by xmlking** [techniq/layerchart#81]
using latest package. 
getting this error 

<img width="1644" alt="image" src="https://github.com/techniq/layerchart/assets/627951/b965e6b9-3e36-465e-94a3-92c11a329d3b">

**Comment by techniq** [comment]
Thanks @xmlking.  I definitely don't want this tight coupling with `daisyui`.  Using top-level exports might require a separate `svelte-ux-daisyui` package (name tbd).  This will definitely be done before published as the official version.  I'm going to track this on the Svelte UX issue.  Thanks again for the report.

**Comment by techniq** [comment]
@xmlking Btw, I just realized I had accidentally overridden the `latest` tag version with `next` after I manually published the last view `next.x` releases.  `latest` is fixed now
