### ISSUE TITLE
Website wrong redirection

### ISSUE THREAD

**Issue by wwmike** [techniq/layerchart#84]
Hello!

I tried to click from svelte-ux github and it was not loading. The browser wrote the redirections are wrong, then I realized it only works with www, without it it goes to an infinite loop. It's might worth checking the DNS settings.

Best,
Mihaly

**Comment by techniq** [comment]
@wwmike Thanks for the heads up.  Was overlooked when I migrated from Vercel to Cloudflare.  Redirect rule is now in place
