### ISSUE TITLE
Move yScale Function to Components – Maintaining PR History

### ISSUE THREAD

**Issue by itsonlyjames** [techniq/layerchart#95]
This is an issue raised for awareness of an old PR feature

Moves the need to apply scaling attributes on individual data elements to the component

[Original fix commit here](https://github.com/techniq/layerchart/commit/2d4bcdad927c2b5dfd49b8a34fde0808397d1c45)

**Comment by techniq** [comment]
This will be nice in the new radial line examples as well - https://github.com/techniq/layerchart/pull/107/files#diff-8c58a8a6dd989abbac04f46081a2ab00f56b734a6399e6b18b9ded8d9a2ceaf0 (still just updating Spline/Area/etc)
