### ISSUE TITLE
Improve Tooltip with multiple series and group/stacked data

### ISSUE THREAD

**Issue by techniq** [techniq/layerchart#98]
Reference:
- https://github.com/techniq/layerchart/issues/21#issuecomment-1809493777
- [discussion](https://discord.com/channels/920755200552226868/1168230758276677762/1204844851640664066)

**Comment by samal-rasmussen** [comment]
I'm trying to get highlight points on multiple series, but am having no luck. The line chart examples only show a single highligt point and only one series data in the tooltip. The stacked area chart is able to show multiple points and  series data in the tooltip. Though it only shows two at a time...

I've tried to pass in a flatData prop with the [12,21, data: data] shape to the line chart, but that just borkes it.

I hate to link out to a different library, but this one has an example of more or less what I'm looking for:
https://apexcharts.com/javascript-chart-demos/line-charts/dashed/

**Comment by techniq** [comment]
@samal-rasmussen Is this what you are looking for?

https://github.com/techniq/layerchart/assets/177476/1f8da6c1-53aa-4d72-ac9d-3f6d8af65513

Fixed via https://github.com/techniq/layerchart/pull/213 and deployed as `0.43.2`

**Comment by samal-rasmussen** [comment]
Yes multiple point highlights just like that, but on a multiple series line chart instead of stacked area chart.

**Comment by techniq** [comment]
@samal-rasmussen `0.43.3` includes PR https://github.com/techniq/layerchart/pull/215 which improves `Highlight` for non-stack array accessors (i.e. series) when displaying points.  I currently need to add a `$key` property to expose the series value key, but hoping a cleaner approach presents itself.

**Comment by techniq** [comment]
@samal-rasmussen Actually I think I came up with a cleaner approach by allowing you to pass an `x` or `y` override to `<Highlight>` (similar to `Area`) and render a separate `<Highlight y={...} points>` for each series).

Available in `0.43.4` and take a look at the "Multiple series (using overrides)" example

**Comment by samal-rasmussen** [comment]
Sean you are an absolute madman. That works perfectly. Tried on `0.43.5`.

**Comment by techniq** [comment]
Ha, glad it works for you :)

**Comment by techniq** [comment]
Better support for tooltips with stacked and/or grouped bar charts are coming in the [Simplified Charts PR](#224).

https://github.com/user-attachments/assets/7225594c-048b-46bd-a13e-fcb0e18ad9c6
